services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:3001
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - jatayu-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://jatayu:password@postgres:5432/jatayu_netra
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=3001
    depends_on:
      - postgres
      - redis
    networks:
      - jatayu-network

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
    networks:
      - jatayu-network

  postgres:
    image: postgis/postgis:14-3.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jatayu
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jatayu_netra
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgresql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - jatayu-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - jatayu-network

volumes:
  postgres_data:

networks:
  jatayu-network:
    driver: bridge